apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "xhgui.fullname" . }}
data:
  config: |-
    <?php
    /**
    * Default configuration for Xhgui
    */
    return array(
        'debug' => false,
        'mode' => 'development',
        'extension' => 'tideways_xhprof',
        'save.handler' => 'mongodb',
        'db.host' => '{{ .Values.mongodb.host }}',
        'db.db' => 'xhprof',
        'db.options' => array(),
        'templates.path' => dirname(__DIR__) . '/src/templates',
        'date.format' => 'Y-m-d H:i:s',
        'detail.count' => 6,
        'page.limit' => 25,
        'profiler.enable' => function() {
            return true;//rand(1, 100) === 42;
        },
        'profiler.simple_url' => function($url) {
            return preg_replace('/\=\d+/', '', $url);
        },
    );



--- 
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "xhgui.fullname" . }}-nginx
data:
  config: |-
    server {
        listen       80;
        server_name  _;

        root   /var/www/html/xhgui-branch/webroot;
        index  index.html index.htm index.php;

        #charset koi8-r;
        access_log /dev/null;
        location / {
            if (!-e $request_filename) {
                rewrite . /index.php  last;
                break;
            }
        }

        location ~ \.php$ {
            fastcgi_pass   127.0.0.1:9000;
            fastcgi_index  index.php;
            fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
            include        fastcgi_params;
        }

    }