apiVersion: v1
kind: Secret
metadata:
  name: {{ template "xhgui.fullname" . }}-sidecar-env
  labels:
    {{- include "xhgui.labels" . | nindent 4 }}
type: Opaque
data:
  {{- include "xhgui.sidecarSecret" . }}
