apiVersion: v1
kind: Service
metadata:
  name: {{ include "hyperf.fullname" . }}
  labels:
    {{- include "hyperf.labels" . | nindent 4}}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "hyperf.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
