ingress:
  enabled: true
  ingressClassName: apisix
  annotations:
    {}
    # cert-manager.io/cluster-issuer: "letsencrypt"
    # kubernetes.io/tls-acme: "true"
    # k8s.apisix.apache.org/http-to-https: "true"
    # k8s.apisix.apache.org/enable-cors: "true"
  hosts:
    - loki.dickens.top
#  tls:
#    - hosts:
#       - loki.dickens.top
#      secretName: loki-distributed-tls
