grafana.ini:
  server:
    domain: grafana.dickens.top
    root_url: "%(protocol)s://%(domain)s/grafana"
    serve_from_sub_path: true
  auth:
    anonymous:
      enabled: true
  security:
    allow_embedding: true # 允许 Iframe 嵌入
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: apisix
    cert-manager.io/cluster-issuer: "letsencrypt"
    kubernetes.io/tls-acme: "true"
    k8s.apisix.apache.org/http-to-https: "true"
  hosts:
    - "grafana.dickens.top"
  path: "/"
  tls: 
    - secretName: grafana-dickens-top-tls
      hosts:
        - grafana.dickens.top
# PVC
persistence:
  enabled: true
  # 自动绑定动态 pv
  # storageClassName: monitoring-grafana-nfs
  size: 2Gi
