apiVersion: v1
kind: Service
metadata:
  name: {{ include "xhgui.fullname" . }}
  labels:
    {{- include "xhgui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - name: sidecar
      port: 9501
      targetPort: 9501
      protocol: TCP
  selector:
    {{- include "xhgui.selectorLabels" . | nindent 4 }}
