apiVersion: v1
kind: Namespace
metadata:
  name: elk
  labels:
    name: elk

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: elasticsearch
  namespace: elk
spec:
  repo: https://helm.elastic.co
  chart: elasticsearch
  targetNamespace: elk
  bootstrap: false
  # set:
  #   adminPassword: "NotVerySafePassword"
  valuesContent: |-
    antiAffinity: "soft"
    # Shrink default JVM heap.
    esJavaOpts: "-Xmx128m -Xms128m"
    # Allocate smaller chunks of memory per pod.
    resources:
      requests:
        cpu: "100m"
        memory: "512M"
      limits:
        cpu: "500m"
        memory: "512M"
    # Request smaller persistent volumes.
    volumeClaimTemplate:
      accessModes: ["ReadWriteOnce"]
      # storageClassName: "standard"
      resources:
        requests:
          storage: 2Gi
