apiVersion: v2
name: apisix
description: A Helm chart for apisix

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version:  2.10.2

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 2.10.1

dependencies:
  - name: etcd
    version: 6.9.4
    repository: https://charts.bitnami.com/bitnami
    condition: etcd.enabled
  - name: apisix-dashboard
    version: 2.9.0
    repository: https://dickens7.github.io/helm-charts
    condition: apisix-dashboard.enabled
  - name: apisix-ingress-controller
    version: 0.8.0
    repository: https://charts.apiseven.com
    condition: apisix-ingress-controller.enabled
