#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

replicaCount: 1
image:
  repository: dickens7/apisix
  pullPolicy: IfNotPresent
  tag: "2.5"
  pullSecrets: []

version: v1

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

gateway:
  type: ClusterIP
  # type: LoadBalancer
  annotations:
    prometheus.io/port: 9080
    prometheus.io/path: /apisix/prometheus/metrics
    prometheus.io/scrape: true
  #   service.beta.kubernetes.io/aws-load-balancer-type: nlb
  http:
    enabled: true
    servicePort: 80
    containerPort: 9080
  tls:
    enabled: false
    servicePort: 443
    containerPort: 9443
    http2:
      enabled: true

  ingress: {}
  #  annotations:
  #    kubernetes.io/ingress.class: traefik
  #    kubernetes.io/tls-acme: "true"
  #  host: apisix.example.local
  #  tls: false


apisixConfig: |-
  apisix:
    enable_admin: true
    enable_debug: false
    enable_control: true
    control:
      ip: "127.0.0.1"
      port: 9090
    admin_key:
      - name: "admin"
        key: edd1c9f034335f136f87ad84b625c8f1
        role: admin
      - name: "viewer"
        key: 4054f7cf07e344346cd3f287985e76a2
        role: viewer
    allow_admin:
      - 127.0.0.0/24 
      - 0.0.0.0/0
  etcd:
    host:
      - "http://etcd-headless.apisix.svc.cluster.local:2379"
    prefix: "/apisix"
    timeout: 30
    # user: root
    # password: 5tHkHhYkjr6cQY
    tls:
      verify: false
  nginx_config:
    error_log: /dev/stdout
    error_log_level: warn
    worker_processes: "1"
    http:
      access_log: /dev/stdout
  plugins:                          # plugin list (sorted in alphabetical order)
    - api-breaker
    - authz-keycloak
    - basic-auth
    - batch-requests
    - consumer-restriction
    - cors
    - echo
    #- error-log-logger
    #- example-plugin
    - fault-injection
    - grpc-transcode
    - hmac-auth
    - http-logger
    - ip-restriction
    - jwt-auth
    - kafka-logger
    - key-auth
    - limit-conn
    - limit-count
    - limit-req
    #- log-rotate
    #- node-status
    - openid-connect
    - prometheus
    - proxy-cache
    - proxy-mirror
    - proxy-rewrite
    - redirect
    - referer-restriction
    - request-id
    - request-validation
    - response-rewrite
    - serverless-post-function
    - serverless-pre-function
    # - skywalking
    - sls-logger
    - syslog
    - tcp-logger
    - udp-logger
    - uri-blocker
    - wolf-rbac
    - zipkin
    - server-info
  plugin_attr:
    skywalking:
      service_name: APISIX
      service_instance_name: "APISIX Instance Name"
      endpoint_addr: http://skywalking-oap.skywalking.svc.cluster.local:12800
  

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
    # cpu: 1000m
    # memory: 256Mi
  requests:
    cpu: 0m
    memory: 0Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

apisix-dashboard:
  enabled: true
  fullnameOverride: "apisix-dashboard"
  image:
    repository: apache/apisix-dashboard
    pullPolicy: IfNotPresent
    tag: "2.5"
  config:
    etcd:
      endpoints:
        - etcd-headless:2379

etcd:
  enabled: true
  fullnameOverride: "etcd"
  auth:
    rbac: 
      enabled: false
      rootPassword: root
  persistence:
    size: 2Gi

etcdkeeper: 
 enabled: true
