apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "rnacos.fullname" . }}
spec:
  serviceName: {{ include "rnacos.fullname" . }}-headless
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "rnacos.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "rnacos.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "rnacos.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/sh
            - /io/entrypoint.sh
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: podinfo
              mountPath: /etc/podinfo
            - mountPath: /io/entrypoint.sh
              name: {{ include "rnacos.fullname" . }}
              subPath: entrypoint.sh
            - name: {{ include "rnacos.fullname" . }}-pvc
              mountPath: /io/nacos_db
      volumes:
        - name: podinfo
          emptyDir: {}
        - name: {{ include "rnacos.fullname" . }}
          configMap:
            name: {{ include "rnacos.fullname" . }}
  volumeClaimTemplates:
  - metadata:
      name: {{ include "rnacos.fullname" . }}-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
