apiVersion: v1
kind: Namespace
metadata:
  name: cilium
  labels:
    name: cilium

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cilium
  namespace: cilium
spec:
  repo: https://helm.cilium.io/
  chart: cilium
  targetNamespace: cilium
  bootstrap: true
  # set:
  #   adminPassword: "NotVerySafePassword"
  valuesContent: |-
    global:
      etcd:
        enabled: true
        managed: true
      hubble:
        enabled: true
        listenAddress: ":4244"
        metrics:
          enabled: "{dns,drop,tcp,flow,port-distribution,icmp,http}"
        relay:
          enabled: true
        ui:
          enabled: true
