apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cilium
  namespace: kube-system
spec:
  repo: https://helm.cilium.io/
  chart: cilium
  targetNamespace: kube-system
  bootstrap: true
  # set:
  #   adminPassword: "NotVerySafePassword"
  valuesContent: |-
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: apisix
          hosts:
            - hubble.dickens.top
    ipam:
      mode: kubernetes
    bpf: 
      masquerade: false