apiVersion: v1
kind: Namespace
metadata:
  name: ingress-apisix
  labels:
    name: ingress-apisix

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: apisix
  namespace: ingress-apisix
spec:
  repo: https://dickens7.github.io/helm-charts/
  chart: apisix
  targetNamespace: ingress-apisix
  # bootstrap: true
  # set:
  #   adminPassword: "NotVerySafePassword"
  valuesContent: |-
    apisixConfig:
      apisix:
        stream_proxy:
          tcp:
            - 9100
          upd:
            - 9200
        admin_key:
          - name: admin
            key: ccuOrnnKFvyF4aA9
            role: admin
    apisix-dashboard:
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: apisix
        ingressClassName: apisix
        hosts:
        - host: apisix-dashboard.dickens.top
          paths:
          - /
    apisix-ingress-controller:
      config:
        apisix:
          adminKey: ccuOrnnKFvyF4aA9
    gateway:
      type: LoadBalancer
      tls:
        enabled: true
    etcd:
      enabled: true
      replicaCount: 1
